spring.application.name=aprendo
server.port=8080
# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Base de datos EN MEMORIA (importante: mem:)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

# Driver de H2
spring.datasource.driver-class-name=org.h2.Driver

# Opcional: para ver SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Fuerza la conexión a la BD en memoria
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
